apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pdf-ocr
  description: A service that extracts text from PDFs and returns it as JSON.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:default/mlteam
  implementsApis:
    - pdf-ocr-api
---
